### ISSUE TITLE
Add return values for methods

### ISSUE THREAD

**Issue by special** [CrimsonAS/qbackend#13]
Right now, any return values from methods are ignored and method calls are always asynchronous. That has led to workarounds involving signals, e.g. within the models. Having real return values would be a good idea.

A few ideas for what this could look like:
```qml
backendObject.invoke("someMethod", function(re) { /* XXX */ }, 12345);
```
```qml
// Automatically add overloads on the object that take a callback
backendObject.someMethod(12345, function(re) { /* XXX */ });
```
This one is interesting because it could also be used to implement explicit blocking calls:
```qml
// Return some kind of temporary object tracking the call
backendObject.someMethod(12345).result(function() { /* XXX */ });
```

**Comment by rburchell** [comment]
You might want to look into ES6 promises.

backendObject.someMethod().then((val) => console.log(val));

**Comment by special** [comment]
> You might want to look into ES6 promises.

Are they usable with QML somehow?
