### ISSUE TITLE
Replace implicit Backend singleton with a way to register singletons explicitly

### ISSUE THREAD

**Issue by rburchell** [CrimsonAS/qbackend#16]
The implicit Backend is an API wart that is a result of early development. Remove it, and replace it with a method to register a singleton instance on the Go side. This could then be transmitted as a normal type to the QML plugin and registered there.

Also removes a layer of complexity from the connection - no more ROOT to deal with, just type registration.

**Comment by special** [comment]
Merged in #22 and e80596459b661252e8d103d5a4ae95e10b607d91
