### ISSUE TITLE
Invert (or allow inverted) process heirarchy

### ISSUE THREAD

**Issue by special** [CrimsonAS/qbackend#4]
I think that applications should launch backend/Go first, and create the UI as a child process or even in-process. My reasoning is:

1. Backend is more interested in commandline data, pre-loading initialization, changing initial UI behavior based on options or state, etc. I think it logically makes sense for it to execute first.
2. The UI side will often be pure-QML and not involve any executables, so it needs to be run via a wrapper like `qmlscene`. The Go side is a real appplication and can be run normally to hide this detail.
3. By putting together a quick cgo package that acts like `qmlscene` (load QML file, start engine; no other interaction), applications can be done with a single binary.
4. When backend is a child process, UI crashes/exits will destroy the backend. If the backend is the parent process, it can stay alive to exit gracefully, restart the UI without losing state, or use this to implement a background mode.

If those aren't convincing enough, it's certainly possible to support this in both directions. The code seems like it should be almost entirely identical.

**Comment by rburchell** [comment]
Irrelevant now.
